name: Gradle CD
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: cd / publish gradle plugins
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: grant execute permission for gradlew on linux systems
        if: runner.os == 'Linux'
        run: chmod +x gradlew
      - name: build
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
